name: Facebook Live Streaming

on:
  workflow_dispatch: # لتشغيله يدويًا
  schedule:
    - cron: '0 * * * *' # لتشغيله كل ساعة (يمكن تعديل الجدول حسب الحاجة)

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: إعداد FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: بدء البث
      env:
        STREAM_URL: "https://video-weaver.cdg10.hls.live-video.net/v1/playlist/Cr4FOxos_evT-DNwpdT_fcUEBIG4Na1hQYTE-E7A6z7erQRTcJcAmLOibrZrfLmOefJuokKpX0-FyN5vK2uQgoZywix6JFewm8m52GFU5BiX-Qd2CoTSaNVxjuJNOlbLgVhDaHjAeKfkga7t6-jf_E1Q2PPjeSD0hDLANEONLmbzvVbBLlAo7JSO8PLrEz-XnHgPXlv_sY10XCRDbjHMME6D2R-J867ifF7MFEQ7tGnC2oT4CQgC7VEIqnuxUmc_eendzP62hniLmllOcwGQKU9TyxumSxo686s0xemv68yeqx29-rYoltEfL5QSy25kIMM1qEmn5n2B6QE-yZslGmqBiggqgsOZFpCHHfHYLEV8__ThOFM6o0a5TDlyjf12RFxI9r1ZZDDdGc5uycp26obw8aAT8ZhBVMTK_0jHoYThGWd5b7NJ4ccvnguRw0cU8RQasIgVBj-Ikd-d9FgR40jgpM25VTGEqdJ0q2NtyukQc_oz-YggoKJfzT5Q1-0G0dFajPFSYvYrH9Bmfw83E_-Isw24nkrBAMwdcx_gJ69WI41hGrr-gskepP_XTjDbalvOjmai_8wjYpf5o1oeRixayJhOz32f6kRvhtAB6SR0hc4z6p5yQ9sJCL3RIAF7rz5eW_jQFJ1s7OTlFPGXHmkUIQyeeWIvVUqd2iZ1BjFOKAzD1Ear-cK_hRSZDBR7dJ1vNXVHws-neeQTwA--fnWhNbFKw1zRTAPPb81rdCGFyXiiaUvmrak0wAYBoui94bh--2lUM0E6a-4fMZUzv8hxVz0LG7oeRwkmcWJwdmY1Cn-WOTRwoQpj0tGUug45e-irYm3UATPJf39UDRU22avh_dFwhUuODYzrPu7iGcND3ntaiqJoDpd-uDLNm6pDGymQpq4cDCfxPY1pXLA7z_ogycG46OTMtTk2pkiMg8TqGgzHZmhr2hJTPJnEdb0gASoJZXUtd2VzdC0yMIYL.m3u8" # رابط M3U8
        STREAM_KEY: "FB-1300409094483260-0-Abw8uhrDwTyNpNHB" # مفتاح البث الخاص بـ Facebook
      run: |
        ffmpeg -re -i "$STREAM_URL" \
        -c:v libx264 -preset veryfast -maxrate 4000k -bufsize 8000k -pix_fmt yuv420p -g 50 \
        -c:a aac -b:a 128k -ar 44100 \
        -f flv "rtmps://live-api-s.facebook.com:443/rtmp/$STREAM_KEY"
