name: Facebook Live Streaming

on:
  workflow_dispatch: # لتشغيله يدويًا
  schedule:
    - cron: '0 * * * *' # لتشغيله كل ساعة (يمكن تعديل الجدول حسب الحاجة)

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: إعداد FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: بدء البث
      env:
        STREAM_URL: "https://video-weaver.cdg10.hls.live-video.net/v1/playlist/CsMFz0yTxrifs64BlkfJIh8E99RItbfi6ElxO0eIqBeECbC3fFi3E0sD3z97yHeWfVcNFDFXk-qz84RrO2o3c044w6G0y8OE6GfvoGNR0hAD1vdQvQbAVmaSCLQiM7Gp1cnm_hDLZMuggMZJ2fqESOdyagynTy3gmtrl2kmKJDLzEqdiXNcq0ZwoN3DdMFjJXvuMgpOGabkVxrEPnvvQoARYe4V3j6AjU1QdWcSU90fKwjiS8-oadA4D8hF1fF-IjDIDvE1-pGCg6DL4LJABIs2jFwzaRQ86xwx8avRjglHa-dCHqQcoEaKn2wQRQBzWBiiP39scNZmM-cwqFwsq7Wjfa_wp0HNX8u1fWO8HViCSN-CkYGqhVpmWQFHqx6IkfocM8uG5FTcgsQsdgC1FgDumE-T2jJ--tGg9NGDdl6N8qWfwRNU_HKn3sbEdYucxgnqP-zeDElv-GAbNqKDm_1w77tFKCJGTaoZvwUb6lRudGqYb8Xl9r8MjJoL0iHFWgw_LDCmQLgI9K2CBcsFRmRcYxJUaxT782UxrppuXN1vmcXT4fD0ry7JO9ol05mTXIOfb-Ox4jNkY3YV9PBFER1JVqJNX48K3aTImZN4LDj90vmd0UX0337yr-1J9Z6XaNx5ALHUabVsZwcMkUxaRUlRc3izPoWhrZcAW4uCWw18vh6QwWjNy92SA7D8tHyrRCu275zA-8N-PbWWcMZpfBwkjL3wfrwchMHk7M61MQ9Xhw9JelONFp_AaDCjcXeRFDqDBJnYbJmsesTbv7cAAAijm1RYkl-0pi-w1HUGuyj3PAZGsAkebgfjTblemXNPTXNiCrhxVdJAo8vzmLc1YHv2mGJbOC9As-uSB_BRpc6NHqxBfZVCucukxlgT8Utit-2oHf5y7wbKRbct-_2QvWv21o3rpFV2yW_i9buEibENF_wDtZnoaDMbn_rvIwqxduSK6QiABKglldS13ZXN0LTIwhQs.m3u8" # رابط M3U8
        STREAM_KEY: "FB-1300407447816758-0-AbwOrkr6btW1Vstm" # مفتاح البث الخاص بـ Facebook
      run: |
        ffmpeg -re -i "$STREAM_URL" \
        -c:v libx264 -preset veryfast -maxrate 4000k -bufsize 8000k -pix_fmt yuv420p -g 50 \
        -c:a aac -b:a 128k -ar 44100 \
        -f flv "rtmps://live-api-s.facebook.com:443/rtmp/$STREAM_KEY"
