name: Facebook Live Streaming

on:
  workflow_dispatch: # لتشغيله يدويًا
  schedule:
    - cron: '0 * * * *' # لتشغيله كل ساعة (يمكن تعديل الجدول حسب الحاجة)

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: إعداد FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: بدء البث
      env:
        STREAM_URL: "https://cdnamd-hls-globecast.akamaized.net/live/ramdisk/2m_monde/hls_video_ts_tuhawxpiemz257adfc/index.m3u8?DVR?t=pmgWJHGUO0DPaPZmcRP7HQ&e=1733357180" # رابط M3U8
        STREAM_KEY: "FB-1298276744696495-0-Abxcqbwldkuwral8" # مفتاح البث الخاص بـ Facebook
      run: |
        ffmpeg -re -i "$STREAM_URL" \
        -c:v libx264 -preset veryfast -maxrate 4000k -bufsize 8000k -pix_fmt yuv420p -g 50 \
        -c:a aac -b:a 128k -ar 44100 \
        -f flv "rtmps://live-api-s.facebook.com:443/rtmp/$STREAM_KEY"
