name: Stream to Facebook Live

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Streaming
        run: |
          ffmpeg -re -i "https://live4.beinconnect.us/YallaGoalApp/beINSports1.m3u8" \
          -c:v libx264 -preset veryfast -c:a aac -b:a 128k -f flv \
          "rtmps://live-api-s.facebook.com:443/rtmp/FB-122146660808365241-0-Abzz_4d144mzvSwr"
