name: Facebook Live Streaming

on:
  workflow_dispatch: # لتشغيله يدويًا
  schedule:
    - cron: '0 * * * *' # لتشغيله كل ساعة (يمكن تعديل الجدول حسب الحاجة)

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: إعداد FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: بدء البث
      env:
        STREAM_URL: "http://bdd78.4rouwanda-shop.store/live/9787488847/index.m3u8?t=Rqvv-cltdpaC0GkcyFuT7Q&e=1733359438" # رابط M3U8
        STREAM_KEY: "FB-1298297644694405-0-Abwa1Iwn1X72Ozci" # مفتاح البث الخاص بـ Facebook
      run: |
        ffmpeg -re -i "$STREAM_URL" \
        -c:v libx264 -preset veryfast -maxrate 4000k -bufsize 8000k -pix_fmt yuv420p -g 50 \
        -c:a aac -b:a 128k -ar 44100 \
        -f flv "rtmps://live-api-s.facebook.com:443/rtmp/$STREAM_KEY"
