name: Facebook Live Streaming

on:
  push:
    branches:
      - main

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up ffmpeg
        run: sudo apt-get install ffmpeg

      - name: Start Streaming to Facebook
        run: |
          # استبدل بـ Stream Key الخاص بك
          STREAM_KEY="FB-122146669922365241-0-Aby18u5VaGKAAj6x"
          
          # رابط الـ M3U8 الذي سيتم بثه
          M3U8_URL="https://live4.beinconnect.us/YallaGoalApp/beINSports1.m3u8"

          echo "Starting stream to Facebook Live..."
          
          # تشغيل ffmpeg لبث الفيديو إلى Facebook
          ffmpeg -i "$M3U8_URL" -c:v libx264 -preset veryfast -g 50 -b:v 1500k -c:a aac -ar 44100 -b:a 128k -f flv "rtmps://live-api-s.facebook.com:443/rtmp/$STREAM_KEY"
